plugins {
    id 'eclipse'
    id 'idea'
    id 'maven-publish'
    alias(nyfs.plugins.mdg)
    alias(nyfs.plugins.hundred.media)
    alias(nyfs.plugins.mod.publish)
}

version = "${minecraft_version}-${mod_version}"
group = mod_group_id
hundredMedia.mcVersion = minecraft_version

base {
    archivesName = mod_id
}

java.toolchain.languageVersion = JavaLanguageVersion.of(17)



println "Java: ${System.getProperty 'java.version'}, JVM: ${System.getProperty 'java.vm.version'} (${System.getProperty 'java.vendor'}), Arch: ${System.getProperty 'os.arch'}"

sourceSets {
    main {
        resources {
            srcDir 'src/generated/resources'
        }
    }

    datagen
}

legacyForge {
    version = nyfs.versions.minecraft.get() + "-" + nyfs.versions.forgeVersionNewest.get()
    def at = file('src/main/resources/META-INF/accesstransformer.cfg')
    if (at.exists()) {
        accessTransformers = [at]
    }
    parchment {
        minecraftVersion = nyfs.versions.parchmentMinecraft.get()
        mappingsVersion = nyfs.versions.parchmentVersion.get()
    }

    mods {
        "${mod_id}" {
            sourceSet sourceSets.main
        }
    }

    runs {
        configureEach {
            jvmArguments = ['-XX:+AllowEnhancedClassRedefinition']
        }
        client {
            client()
        }
        server {
            server()
        }
        data {
            data()
            programArguments.addAll '--mod', mod_id, '--all', '--output', file('src/generated/resources/').getAbsolutePath(), '--existing', file('src/main/resources/').getAbsolutePath()
        }
    }
}

mixin {
    add(sourceSets.main, "${mod_id}.refmap.json")
    config("${mod_id}.mixins.json")
}

configurations {
    datagenCompileClasspath.extendsFrom compileClasspath
    datagenRuntimeClasspath.extendsFrom runtimeClasspath
}

repositories {
    maven hundredMedia.get100MediaMaven()
}

dependencies {
    datagenImplementation sourceSets.main.output
    annotationProcessor(nyfs.mixin) {
        artifact {
            classifier = 'processor'
        }
    }

    annotationProcessor(nyfs.mixin.extras.common)
    implementation(nyfs.mixin.extras.common)
    implementation(nyfs.mixin.extras.forge)
    jarJar(nyfs.mixin.extras.forge)

    modImplementation(nyfs.cap.syncer)
    jarJar(nyfs.cap.syncer)

    modRuntimeOnly("com.harleyoconnor.suggestionproviderfix:SuggestionProviderFix-${minecraft_version}:${suggestion_provider_fix_version}")
    modImplementation("curse.maven:irons-spells-n-spellbooks-855414:5539243")
    modImplementation("curse.maven:caelus-308989:5281700")
    modImplementation("curse.maven:curios-309927:5367944")
    modImplementation("curse.maven:playeranimator-658587:4587214")
    modImplementation("curse.maven:geckolib-388172:5460309")
    modImplementation("curse.maven:jei-238222:5621194")
    modImplementation("curse.maven:ars-nouveau-401955:5436131")
    modImplementation("curse.maven:apothic-attributes-898963:5634071")
    modImplementation("curse.maven:placebo-283644:5414631")
    modImplementation("curse.maven:apotheosis-313970:5317303")
    modImplementation("curse.maven:apothic-curios-950712:5352974")
    modImplementation("curse.maven:electroblobs-wizardry-redux-1405790:7643996")
    modImplementation("curse.maven:put-mana-in-1194625:7028850")
}

tasks.withType(ProcessResources).configureEach {
    var replaceProperties = [
        minecraft_version: minecraft_version,
        minecraft_version_range: nyfs.versions.minecraftVersionRange.get(),
        forge_version: nyfs.versions.forgeVersion.get(),
        forge_version_range: nyfs.versions.forgeVersionRange.get(),
        loader_version_range: nyfs.versions.forgeLoaderRange.get(),
        mod_id: mod_id, mod_name: mod_name, mod_license: mod_license, mod_version: mod_version,
        mod_authors: mod_authors, mod_description: mod_description
    ]
    inputs.properties replaceProperties

    var replaceTargets = [
            'META-INF/mods.toml', 'pack.mcmeta', "${mod_id}.mixins.json".toString(),
            "assets/${mod_id}/blockstates/hundred_media.json".toString(),
            "assets/${mod_id}/models/block/hundred_media.json".toString(),
            "assets/${mod_id}/models/item/hundred_media.json".toString()
    ]
    filesMatching(replaceTargets) {
        expand replaceProperties + [project: project]
    }
}

java {
    withSourcesJar()
}

tasks.named('jar', Jar).configure {
    archiveClassifier = ''
    manifest {
        attributes([
                'Specification-Title': mod_id,
                'Specification-Vendor': mod_authors,
                'Specification-Version': '1',
                'Implementation-Title': project.name,
                'Implementation-Version': mod_version,
                'Implementation-Vendor': mod_authors,
                'Implementation-Timestamp': new Date().format('yyyy-MM-dd\'T\'HH:mm:ssZ')
        ])
    }
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}




jar {
    jar.finalizedBy reobfJar
    manifest.attributes([
            "MixinConfigs": "${mod_id}.mixins.json"
    ])
}



publishMods {
    file = reobfJar.archiveFile
    changelog = file("new_changelog.md").text
    type = STABLE
    modLoaders.add("neoforge")
    modLoaders.add("forge")
    displayName = "${mod_name}-${minecraft_version}-[NeoForge]-${project.version}"
    dryRun = dry_run.toBoolean()
    if (curseforge_publishing_enabled.toBoolean()) {
        curseforge {
            projectId = curseforge_project_id
            accessToken = curseforge_token
            minecraftVersions.add(minecraft_version)
            clientRequired = true
            serverRequired = true
            javaVersions.add(JavaVersion.VERSION_17)
        }
    }
    if (modrinth_publishing_enabled.toBoolean()) {
        modrinth {
            accessToken = modrinth_token
            projectId = modrinth_project_id
            minecraftVersions.add(minecraft_version)
        }
    }
}
