org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

minecraft_version=1.20.1

mod_id=manaunification
mod_name=Mana Unification Mod
mod_license=All Rights Reserved
mod_version=2.0.0-SNAPSHOT-5
mod_group_id=com.nyfaria.manaunification
mod_authors=Nyfaria
mod_description=Unifies Mana between Spell Casting Mods.

suggestion_provider_fix_version=1.0.0

curseforge_publishing_enabled=true
curseforge_project_id=1083306
modrinth_publishing_enabled=true
modrinth_project_id=VC9P1w0f
dry_run=false